node {
   def commit_id
   stage('Preparation') {
     checkout scm
    
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       bat 'npm install --only=dev'
       bat 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'docker1') {
       def app = docker.build("shwethsoma123456/shwetha123:${commit_id}", '.').push()
     }
   }
}
